### ISSUE TITLE
How can I install this SDK with Maven

### ISSUE THREAD

**Issue by wohhie** [iotsens/iotsens-api-sdk#2]
How can I install it on my local repository executing "mvn install" in the root folder of the project?
I will appreciate if you give me any sample how to integrate. I didn't find any sample.

**Comment by JavierMF** [comment]
Using a command-line terminal, navigate to the root folder of the SDK project and execute "mvn install". The SDK will be compiled, packaged and installed in your local repository of .jar files. You will need Maven installed. http://maven.apache.org/plugins/maven-install-plugin/usage.html

**Comment by wohhie** [comment]
I already create the jar files including class files using "maven install". I also import the jar file as a library in the project. But it didn't work. I will appreciate if you give me a way forward what have to do after generating the jar file.

Regards

**Comment by JavierMF** [comment]
Once the library has been installed you can use it as any other regular dependency. If you are using maven, you can include de dependency as:
<dependency>
<groupId>iotsens-api-sdk</groupId>
    <artifactId>iotsens-api-sdk</artifactId>
    <version>1.4</version>
</dependency>

**Comment by JavierMF** [comment]
Dear @wohhie ,

We have published the library on jitpack.io, so now it can be added to the pom without local install.
You can find the instructions here: https://jitpack.io/#iotsens/iotsens-api-sdk
